server:
  port: ${PORT:8080}
  servlet:
    context-path: /

springdoc:
  swagger-ui:
    path: /swagger-ui.html

app:
  data-gov:
    api-key: ${DATA_GOV_API_KEY:579b464db66ec23bdd000001cdd3946e44ce4aad7209ff7b23ac571b}
